version: '3.3'

services:
  redis:
    image: redis
  chat:
    build: ./
    ports:
    - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    volumes:
    - ./:/opt/chat